[project]
name = "daily-profit-model"
version = "0.1.0"
description = "A predictive model to score trading accounts based on the likelihood and magnitude of making profits, aiding in hedging decisions."
readme = "README.md"
requires-python = ">=3.13"
authors = [
    { name = "Carlos Rico-Ospina", email = "carlosricojr@gmail.com" }
]
keywords = ["finance", "prop trading", "machine learning", "hedging", "prediction"]

dependencies = [
    "lightgbm>=4.6.0",
    "numpy>=2.2.6",
    "optuna>=4.3.0",
    "pandas>=2.2.3",
    "psycopg2-binary>=2.9.10",
    "python-dotenv>=1.1.0",
    "requests>=2.32.3",
    "scikit-learn>=1.6.1",
    "shap>=0.47.2",
    "tqdm>=4.67.1",
]

[project.urls]
"Homepage" = "localhost:69420" # Update if you have one
"Repository" = "https://github.com/carlosricojr/daily-profit-model"

[build-system]
requires = ["uv>=0.2.0"]
build-backend = "uv"